# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ms_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 920)
        MainWindow.setMaximumSize(QtCore.QSize(1034, 920))
        MainWindow.setStyleSheet("background-color: #ffa69e;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #ffa69e;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(40, 40, 40, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.stackedWidgetPage1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.stackedWidgetPage1)
        self.frame_4.setStyleSheet("background-color: #FF686B;\n"
"border-bottom-right-radius: 40px;\n"
"border-top-left-radius:40px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.stackedWidgetPage2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.stackedWidgetPage2)
        self.frame_5.setStyleSheet("background-color: #FF686B;\n"
"border-bottom-right-radius: 40px;\n"
"border-top-left-radius:40px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(50, 50, 50, 50)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.video_label = QtWidgets.QLabel(self.frame_5)
        self.video_label.setStyleSheet("border-radius:50px;")
        self.video_label.setText("")
        self.video_label.setObjectName("video_label")
        self.horizontalLayout_6.addWidget(self.video_label)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.stackedWidgetPage3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.stackedWidgetPage3)
        self.frame_6.setStyleSheet("background-color: #FF686B;\n"
"border-bottom-right-radius: 40px;\n"
"border-top-left-radius:40px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.stackedWidgetPage3)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setStyleSheet("background-color: #84DCC6;\n"
"border-top-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(50, 30, 50, 40)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background: transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 12)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_about = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_about.sizePolicy().hasHeightForWidth())
        self.Btn_about.setSizePolicy(sizePolicy)
        self.Btn_about.setMinimumSize(QtCore.QSize(200, 25))
        self.Btn_about.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.Btn_about.setFont(font)
        self.Btn_about.setStyleSheet("QPushButton{\n"
" background-color: #ffffff;\n"
" border: 1px solid #ffffff;\n"
" color:#FF686B; \n"
" border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
" background-color:  #A5FFD6;\n"
" border: 1px solid #A5FFD6;\n"
" color:#3c3c3c;\n"
"}")
        self.Btn_about.setObjectName("Btn_about")
        self.horizontalLayout_2.addWidget(self.Btn_about)
        self.Btn_emotion = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_emotion.sizePolicy().hasHeightForWidth())
        self.Btn_emotion.setSizePolicy(sizePolicy)
        self.Btn_emotion.setMinimumSize(QtCore.QSize(0, 25))
        self.Btn_emotion.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.Btn_emotion.setFont(font)
        self.Btn_emotion.setStyleSheet("QPushButton{\n"
" background-color: #ffffff;\n"
" border: 1px solid #ffffff;\n"
" color:#FF686B; \n"
" border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
" background-color:  #A5FFD6;\n"
" border: 1px solid #A5FFD6;\n"
" color:#3c3c3c;\n"
"}")
        self.Btn_emotion.setObjectName("Btn_emotion")
        self.horizontalLayout_2.addWidget(self.Btn_emotion)
        self.Btn_capture = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_capture.sizePolicy().hasHeightForWidth())
        self.Btn_capture.setSizePolicy(sizePolicy)
        self.Btn_capture.setMinimumSize(QtCore.QSize(0, 25))
        self.Btn_capture.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.Btn_capture.setFont(font)
        self.Btn_capture.setStyleSheet("QPushButton{\n"
" background-color: #ffffff;\n"
" border: 1px solid #ffffff;\n"
" color:#FF686B; \n"
" border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
" background-color:  #A5FFD6;\n"
" border: 1px solid #A5FFD6;\n"
" color:#3c3c3c;\n"
"}")
        self.Btn_capture.setObjectName("Btn_capture")
        self.horizontalLayout_2.addWidget(self.Btn_capture)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_3.setStyleSheet("background: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(30, 5, 30, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777190, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #A5FFD6;\n"
"color: #579484")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_about.setText(_translate("MainWindow", "About"))
        self.Btn_emotion.setText(_translate("MainWindow", "Emotion Detection"))
        self.Btn_capture.setText(_translate("MainWindow", "Screen Capture"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">c.b anasuya &amp; akaash</p></body></html>"))
